export const techMap: {[key: string]: string} = {
    javascript: "devicon-javascript-plain",
    js: "devicon-javascript-plain colored",
    typescript: "devicon-typescript-plain",
    ts: "devicon-typescript-plain",
    react: "devicon-react-original",
    nextjs: "devicon-nextjs-plain",
    next: "devicon-next-plain",
    nodejs: "devicon-nodejs-plain",
    node: "devicon-node-plain",
    python: "devicon-python-plain",
    java: "devicon-java-plain",
    css: "devicon-css-plain",
    git: "devicon-git-plain",
    php: "devicon-php-plain",
    "c++": "devicon-cplusplus-plain",
    cpp: "devicon-cplusplus-plain",
    "c#": "devicon-csharp-plain",  
    csharp: "devicon-csharp-plain",
  };